### PR TITLE
Fixes #94, #96

### LINKED ISSUE #94: LoadFromString is unnecessary and wrong
In #93 the LoadFromString method was added to the D2D and Pas factories.  This was unnecessary and wrong.

The proper way of loading from a string is to use the Source property of ISVG.  This also sets the FSource field of the underlying D2D implementation.

Please remove LoadFromString.

### PR DESCRIPTION
**Pull request by pyscripter**
Now uses XMLLite.

uDataModule with around 300 svgs loads twice as fast. (30ms in my machine)  With D2D is around 15ms,  so D2D is still faster but the performance gap has been slashed.  And painting is a bit faster with TSVG.
Loading cowboy.svg is down from the original 160ms to 45ms on my machine.

With the further optimizations cowboy.pas loads in 36 ms and uDataModule loads in 27ms.

@vincentparrett 
@carloBarazzetta 
Could you please do some benchmarking at your side?  And testing to make sure I haven't broken something...

### CODE REVIEW

**Comment by carloBarazzetta** [comment]
Okay, I'll do some benchmarks and tests.

**Comment by vincentparrett** [comment]
So far so good.. all seems to work fine. I did notice though that XmlLite wasn't added to the SVGIconPackage so it's being implicitly imported (and generating a warning).

**Comment by carloBarazzetta** [comment]
Ok, I'm adding the unit and updating all packages, also removing unit SVGProperties.pas.

**Comment by carloBarazzetta** [comment]
Benchmark:
old loading 655 Papirus Icons in 2.500 msec - new in 1.578 msec
old loading 5.366 material design icons in 21.828 msec - new in 11.969
A very good job!

**Comment by the-Arioch** [comment]
should this mean this wrapper was de facto tested with win64 not only win32?

**Comment by the-Arioch** [comment]
> the pascal backend has been removed. 

But why? i lurked a bit around and i saw another ticket, there you(?) said that optimized TSVG was on par with cairo by speed?

> XMLLite rocks however.

there was also, i heard, a 3rd-party (maybe WinE but i think not) implementation for Linux. I wonder if anyone did speed tests on Linux.

I remember we were getting some bank reports, they were most probably made crazy way, the infinite loops creating more and mmmore empty columns and rows in Excel until it threwe errors. 99% of those files were empty XML structures. OpenOffice choked on those and even Excel went noticably slow. I then tried usual MSXML/DOM (TXMLDocument), OmniXML (even made small patches to XPath and `Node[i+1]/NextSibling` thinies), but they were terribly slow still. XMLLite was a saviour indeed.

**Pull request merged**
