### PR TITLE
Implemented CalcRect using the Delphi RTL as FittedRect

### PR DESCRIPTION
**Pull request by pyscripter**
Implemented CalcRect using the Delphi RTL as FittedRect and moved to SVGCommon.pas
Removed unused GDIPUtils.pas
Fixed the line-ends (Unix to Windows) of a few files. (I think that is where the conflicts come from...)

@carloBarazzetta 
Many of the files have Unix line-endings.  Please check your git client to avoid automatic conversions.
There are now 3 files in the GDI folder.  They could be moved to the SVG folder to avoid having to add an extra folder to the Delphi search path.  What do you think?

### CODE REVIEW

**Comment by carloBarazzetta** [comment]
"There are now 3 files in the GDI folder. They could be moved to the SVG folder to avoid having to add an extra folder to the Delphi search path. What do you think?"
I agree!

**Comment by pyscripter** [comment]
> "There are now 3 files in the GDI folder. They could be moved to the SVG folder to avoid having to add an extra folder to the Delphi search path. What do you think?"
> I agree!

I will do it.  But could you first manually merge this PR? You can manually merge the conflicts by using my version.

**Comment by pyscripter** [comment]
I am done for now regarding improvements to TSVG.  The work included
- numerous parsing and rendering fixes (related to transforms, gradients, style sheets, % units and more).  I think it looks good now.
- quite a few performance improvements but clearly there is scope for more.
- code refactoring to make it easier to work with and maintain. 

@carloBarazzetta 
- Could you please:
-  merge this PR.  
- check the FMX side.  I hope I did not break that.
- convert all files to Windows line-ends, so that they don't get messed up when you edit them in Delphi. (avoid auto conversion)
- remove the GDIP folder and move its contents to SVG.

Thank you!

**Comment by carloBarazzetta** [comment]
Ok, today I'm working to manually take the changes from your Git repository to mine because this PR has conflicts.

**Comment by carloBarazzetta** [comment]
Pull Request acquired!
Merged all of your code (except for FileName of TSVGIconImage)
Three units moved from GDIP to Svg (and updated Packages files for this reason)

**Comment by carloBarazzetta** [comment]
Sorry i was forgetting to convert the EOL of files. Now I have committed all files with CR + LF, let me know if they are ok!

**Comment by pyscripter** [comment]
@carloBarazzetta 
Thanks very much.   That's great!

- The EOL is still not fully resolved.  There are still files with lf endings (e,g. Svg\SVGColor.pas and quite a few others)
- In TSVGIconImageListBase.LoadFromFiles you need to check that SVGIconItems is not nil.
- In unit SVGIconImageList you can remove  System.UITypes and the conditional define from the uses list.  I don't think it is used.

**Comment by carloBarazzetta** [comment]
Ok. sorry for EOL, but my Git was configured with "--global core.autocrlf true" and I using Tortoise Git the EOL files was automatically converted, so on my disk the files were ok. Now I have fixed all files, please check if all files are now okay!
Thank you.

**Comment by pyscripter** [comment]
The EOL are now fine.  Thanks.

**Pull request closed without merging**
