### PR TITLE
Fixes #26, #27, #28, #29, #30, #33 #34

### LINKED ISSUE #26: Error in CalcMartrix
When you apply multiple transformations you pre-multiply the new one with the old one. See for example CalcRootMatrix where it is done correctly. However in TSVGMatrix.CalcMatrix it is done the wrong way (post-multiply the new matrix).

You need to change:

CompleteMatrix := CompleteMatrix * NewMatrix;
to
CompleteMatrix := NewMatrix * CompleteMatrix;

and
LMatrix := LMatrix * NewMatrix;
to
LMatrix := NewMatrix * LMatrix;

Also the "fix"
```pascal
          //Fix for transform:translate with rescaling
          NewMatrix.m31 := NewMatrix.m31 * ADX;
          NewMatrix.m32 := NewMatrix.m32 * ADY;
```
is just wrong.  Please remove.  

Finally CalculateMatrices and CalcMatrix do not need any arguments.  AX, AY, ADX, AD are taken care of by the transformations in CalcRootMatrix. 

You can test the above with the attached sgv.
[Back3.zip](https://github.com/EtheaDev/SVGIconImageList/files/5046457/Back3.zip)

### PR DESCRIPTION
**Pull request by pyscripter**
With the above changes it will be possible to parse a much wider range of svgs.

### CODE REVIEW

**Comment by pyscripter** [comment]
With this PR TSVG is on a par with Windows support and it supports text which Windows doesn't. (see https://docs.microsoft.com/en-us/windows/win32/direct2d/svg-support).

Of course there are still bugs and glitches, and there is massive scope for performance improvements.   But I think that they are fixable.

@vincentparrett Could you please test your svg files with this PR?

**Comment by vincentparrett** [comment]
Looks good, I don't see any changes to my svg's. I have around 1000 to generate/create/find for this project and only have around 30 so far so it's hardly an exhaustive test.

**Comment by pyscripter** [comment]
If you are looking for flat monochrome icons https://materialdesignicons.com/ is good and free.   https://www.flaticon.com/ offers wider choice but requires attribution.

**Comment by pyscripter** [comment]
Here are some svgs for testing the fixes.
[Svg.zip](https://github.com/EtheaDev/SVGIconImageList/files/5054421/Svg.zip)

**Comment by carloBarazzetta** [comment]
Hi Kiriakos Vlahos, I've merged your pull request in the main branch, updated readme, documentation, wiki, icons of components, images... and created official v.1.8 version.
Thank you for your great job to fix the rendering engine!

**Comment by pyscripter** [comment]
Thank you!
There is more coming!

**Pull request merged**
